name: Project Catalyst Node.js CI 

on:
  push:
    branches: [ wiki, graphql ]
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
      with:
        ref: graphql
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: create env file
      run: |
        touch .env
        echo WIKIJS_API_TOKEN=${{ secrets.WIKIJS_API_TOKEN}} >> .env
        echo WIKIJS_GRAPHQL_ENDPOINT=${{secrets.WIKIJS_GRAPHQL_ENDPOINT}} >> .env
    - name: Build html 
      run: yarn build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./html
        cname: cardanocataly.st
